# Generated by Django 2.1 on 2018-08-24 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nation', '0004_conservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conservation',
            old_name='typ_e',
            new_name='type',
        ),
    ]
