# Generated by Django 2.1 on 2018-08-16 11:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nepal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist_id', models.IntegerField()),
                ('district', models.CharField(max_length=18)),
                ('zone_name', models.CharField(max_length=16)),
                ('region', models.CharField(max_length=16)),
                ('diss', models.IntegerField()),
                ('xc', models.FloatField()),
                ('yc', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
